/**
 * Tasks for the model-economy widget. Evergreen - no vendor facts, no model
 * names, no prices. Encodes the per-task spend judgment from the course
 * models chapters (claude-code/models-thinking/cost.mdx,
 * codex/models-effort/cost-aware.mdx, copilot/models/credits.mdx,
 * cursor/models/index.mdx, opencode/providers-models/per-agent-model.mdx):
 * two independent dials - which model answers, how hard it thinks - with the
 * matched corners on the diagonal and both off-diagonal corners leaking.
 * The cost model is deliberately coarse: a capable model bills ~5× per
 * token, high effort generates ~3× the tokens, and an underpowered hard
 * task pays a redo tax (failed attempts plus the escalation you do anyway).
 * The ratios are the point, not the numbers.
 */

export type MdeModel = 'light' | 'capable';
export type MdeEffort = 'low' | 'high';
export type MdeCorner = `${MdeModel}/${MdeEffort}`;

/** Relative cost per token by model */
export const MDE_MODEL_MULT: Record<MdeModel, number> = {
  light: 1,
  capable: 5,
};

/** Relative tokens generated by effort */
export const MDE_EFFORT_MULT: Record<MdeEffort, number> = {
  low: 1,
  high: 3,
};

export const MDE_MODEL_LABELS: Record<MdeModel, string> = {
  light: 'light',
  capable: 'capable',
};

export const MDE_EFFORT_LABELS: Record<MdeEffort, string> = {
  low: 'low',
  high: 'high',
};

export interface MdeVerdict {
  /** Chip label shown for this corner */
  chip: string;
  tone: 'good' | 'warn' | 'bad';
  /** One-line explanation of the verdict */
  why: string;
}

export interface MdeTask {
  id: string;
  /** Short row title */
  label: string;
  /** Kind + how often it comes up today, shown next to the label */
  cadence: string;
  /** The task itself */
  text: string;
  /** Times it comes up today */
  count: number;
  /** Spend units per occurrence on the light model at low effort */
  size: number;
  /** True when an underpowered run fails and pays the redo tax */
  hard: boolean;
  /** The corner that wins */
  best: MdeCorner;
  verdicts: Record<MdeCorner, MdeVerdict>;
}

export const mdeTasks: MdeTask[] = [
  {
    id: 'copy',
    label: 'copy tweaks',
    cadence: 'mechanical · five today',
    text: 'Fix the onboarding typo, reword two error strings, update the footer year - one obvious answer each.',
    count: 5,
    size: 1,
    hard: false,
    best: 'light/low',
    verdicts: {
      'light/low': {
        chip: 'matched - cheapest corner that works',
        tone: 'good',
        why: 'One obvious answer per tweak. Extra reasoning can’t improve a typo fix; it can only make it cost more and arrive later.',
      },
      'light/high': {
        chip: 'deliberating on the obvious',
        tone: 'warn',
        why: 'High effort makes the model generate three times the thinking for a task with nothing to think about. Same one-line diff, triple the tokens, slower.',
      },
      'capable/low': {
        chip: 'overpowered - ~5× for the same diff',
        tone: 'warn',
        why: 'The capable model bills ~5× per token to produce the identical tweak. Five times today, that’s a habit, not a splurge.',
      },
      'capable/high': {
        chip: 'top dollar, one answer',
        tone: 'warn',
        why: 'The most expensive corner on the board, spent on work the cheap corner ships identically. This is where a pinned dial leaks.',
      },
    },
  },
  {
    id: 'crud',
    label: 'pattern-following endpoints',
    cadence: 'mechanical · three today',
    text: 'Add list/create endpoints that mirror the handler in the next file over.',
    count: 3,
    size: 4,
    hard: false,
    best: 'light/low',
    verdicts: {
      'light/low': {
        chip: 'matched - the pattern does the reasoning',
        tone: 'good',
        why: 'The file next door already answered every design question. The model’s job is transcription with fresh names - light and shallow covers it.',
      },
      'light/high': {
        chip: 'thinking the task doesn’t need',
        tone: 'warn',
        why: 'Deep effort re-derives decisions the existing pattern already made. Triple the tokens to arrive where copying would have.',
      },
      'capable/low': {
        chip: 'a brain you’re idling',
        tone: 'warn',
        why: 'It ships fine - capable models do boilerplate beautifully. But it’s ~5× per token for the same four routes, three times today.',
      },
      'capable/high': {
        chip: 'premium for boilerplate',
        tone: 'warn',
        why: 'Nothing about list/create forks or surprises; the expensive reasoning has nothing to grip. Reserve this corner.',
      },
    },
  },
  {
    id: 'race',
    label: 'the intermittent failure',
    cadence: 'hard · once, thankfully',
    text: 'A test that fails one run in five, timing-dependent, with the cause three files from the symptom.',
    count: 1,
    size: 8,
    hard: true,
    best: 'capable/high',
    verdicts: {
      'light/low': {
        chip: 'underpowered - flails, then you escalate',
        tone: 'bad',
        why: 'It pattern-matches a plausible fix, the test still flakes, twice more, and you hand it to the big model anyway. The redo tax beats starting there - and you read every wrong answer along the way.',
      },
      'light/high': {
        chip: 'thinking a light brain can’t cash',
        tone: 'bad',
        why: 'Triple the thinking tokens buys deliberation, not capability. The model deliberates its way to the same wrong fix - the most expensive way to fail.',
      },
      'capable/low': {
        chip: 'a coin flip',
        tone: 'warn',
        why: 'The right brain without the reasoning budget to search the interleavings. You get a confident answer fast; whether it found the race or a race is what your review has to catch.',
      },
      'capable/high': {
        chip: 'matched - spend it here',
        tone: 'good',
        why: 'A genuine reasoning problem: timing-dependent, cause far from symptom, no pattern to copy. This corner exists for exactly this task.',
      },
    },
  },
  {
    id: 'fork',
    label: 'the design fork',
    cadence: 'hard · once',
    text: 'Choose how rule conflicts resolve in the categorisation engine - several defensible designs, one gets built on.',
    count: 1,
    size: 8,
    hard: true,
    best: 'capable/high',
    verdicts: {
      'light/low': {
        chip: 'underpowered - picks without weighing',
        tone: 'bad',
        why: 'It commits to the first workable-looking option. A design fork answered wrong isn’t a retry - it’s a rewrite after you’ve built on the answer.',
      },
      'light/high': {
        chip: 'deliberate, still shallow',
        tone: 'bad',
        why: 'More thinking on a light model widens the prose, not the analysis. The trade-offs it can’t see at low effort it still can’t see at high.',
      },
      'capable/low': {
        chip: 'a coin flip on a fork',
        tone: 'warn',
        why: 'Capable but shallow means the first defensible design, argued confidently. Forks are precisely where you want the alternatives actually explored before one wins.',
      },
      'capable/high': {
        chip: 'matched - the wrong call costs a rewrite',
        tone: 'good',
        why: 'Several reasonable designs, and whichever wins gets built on. The delta between corners here is noise next to the cost of unpicking a bad choice later.',
      },
    },
  },
];
